### ISSUE TITLE
v0.1 Roadmap

### ISSUE THREAD

**Issue by kerryChen95** [kerryChen95/vue-long-list#1]
* [x] only support all items has uniform sizes, may support vairable sizes in the future
* [x] only support scroll on y-axis, may support on x-axis in the future
* [x] support multiple items per line
* [x] delete any invisible or visible items by change list data, the long list still works
